const FETCH_ALL_STORIES = 'FETCH_ALL_STORIES';
const CREATE_STORY = 'CREATE_STORY';
const UPDATE_STORY = 'UPDATE_STORY';
const DELETE_STORY = 'DELETE_STORY';

const AUTHENTICATION = 'AUTHENTICATION';
const LOGOUT = 'LOGOUT';

const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
const UPDATE_USER = 'UPDATE_USER';
const DELETE_USER = 'DELETE_USER';

const FETCH_ALL_CONVERSATIONS = 'FETCH_ALL_CONVERSATIONS'; 
const NEW_CONVERSATION = 'NEW_CONVERSATION';
const DELETE_CONVERSATION = 'DELETE_CONVERSATION';

const FETCH_ALL_MESSAGES = 'FETCH_ALL_MESSAGES'; 
const NEW_MESSAGE = 'NEW_MESSAGE';

export {
  FETCH_ALL_STORIES,
  CREATE_STORY,
  UPDATE_STORY,
  DELETE_STORY,
  AUTHENTICATION,
  LOGOUT,
  FETCH_ALL_USERS,
  UPDATE_USER,
  DELETE_USER,
  FETCH_ALL_CONVERSATIONS,
  NEW_CONVERSATION,
  DELETE_CONVERSATION,
  FETCH_ALL_MESSAGES,
  NEW_MESSAGE,
};
